Add -e/--daily-expiry option
Because:

* The frequency which freshclam updates is configurable, so the 90
  minute default may not be approapriate in all cases.

Notes:

* freshclam defaults to once per hour on Ubuntu trusty, but once every 2
  hours on Gentoo.

diff --git a/check_clamav_signatures b/check_clamav_signatures
--- a/check_clamav_signatures
+++ b/check_clamav_signatures
@@ -46,11 +46,16 @@ help() {
   Examples:
     ./check_clamav_signatures
 
+    ./check_clamav_signatures --expiry '1 day'
+
   Options:
+    -e, --expiry <duration>      duration before the daily signatures are considered expired
     -l, --clam-lib-path <dir>    path to ClamAV lib directory, default: $CLAM_LIB_DIR
     -s, --state-file-path <dir>  path to state file directory, default: $STATE_FILE_DIR
     -V, --version                output version
     -h, --help                   output help information
+
+  -e/--expiry should be a human readable duration, e.g. '1 hour', or '7 days'.
 
   For more information, see https://github.com/tommarshall/nagios-check-clamav-signatures
 
@@ -64,6 +69,7 @@ EOF
 while test $# -ne 0; do
   ARG=$1; shift
   case $ARG in
+    -e|--expiry) EXPIRY_THRESHOLD=$1; shift ;;
     -l|--clam-lib-path) CLAM_LIB_DIR=$1; shift ;;
     -s|--state-file-path) STATE_FILE_DIR=$1; shift ;;
     -V|--version) version; exit ;;
@@ -87,6 +93,12 @@ for dependency in cut host grep sigtool sed; do
     exit $UNKNOWN
   fi
 done
+
+# ensure the daily expiry argument is valid
+if ! EXPIRY_THRESHOLD_TIMESTAMP="$(date --date="-$EXPIRY_THRESHOLD" +'%s' 2>/dev/null)"; then
+  echo "UNKNOWN: Invalid daily expiry duration specified: ${EXPIRY_THRESHOLD}"
+  exit $UNKNOWN
+fi
 
 # ensure the clam lib dir exists
 if [ ! -d "$CLAM_LIB_DIR" ]; then
@@ -149,9 +161,8 @@ if ! [[ $CURRENT_MAIN_VERSION =~ $NUMERICAL_REGEX ]]; then
   exit $UNKNOWN
 fi
 
-# get the daily signatures timestamps
+# get the last OK timestamp from the state file
 LAST_OK_TIMESTAMP="$(stat --format='%Y' $STATE_FILE_DIR/$STATE_FILE_NAME 2>/dev/null || echo '0')"
-EXPIRY_THRESHOLD_TIMESTAMP="$(date --date="-$EXPIRY_THRESHOLD" +'%s')"
 
 # determine the difference between the current and installed versions
 DAILY_VERSION_DELTA=$((CURRENT_DAILY_VERSION-INSTALLED_DAILY_VERSION))
