Add expiry threshold for daily signatures
Because:

* There is a race between freshclam and the check when a new daily
  version is published. If the check runs before freshclam then a
  CRITICAL is reported. The check will then go back to an OK once
  freshclam runs.
* In this scenario the signatures are correctly being updated, so the
  check should remain OK throughout.

This change:

* Introduces an expiry threshold, which defaults to 90 minutes.
* If the installed daily signatures version is behind the the current
  version from the DNS record, but the check was OK within the threshold
  then freshclam is considered to be running correctly and the check
  exits OK, with a message about the threshold.
* The threshold is implemented via a state file, which is written to
  `/var/lib/nagios/.check_clamav_signatures_ok` by default. The dir can
  be overridden by the -s/--state-file-path option.
* The main signatures do not currently have the expiry threshold.

Fixes #2

diff --git a/check_clamav_signatures b/check_clamav_signatures
--- a/check_clamav_signatures
+++ b/check_clamav_signatures
@@ -15,6 +15,9 @@ CRITICAL=2
 UNKNOWN=3
 CLAM_LIB_DIR=/var/lib/clamav
 NUMERICAL_REGEX='^[0-9]+$'
+EXPIRY_THRESHOLD='90 minutes'
+STATE_FILE_DIR=/var/lib/nagios
+STATE_FILE_NAME=.check_clamav_signatures_ok
 
 #
 # Output version.
@@ -44,9 +47,10 @@ help() {
     ./check_clamav_signatures
 
   Options:
-    -l, --clam-lib-path <path>  path to ClamAV lib directory, if not $CLAM_LIB_DIR
-    -V, --version               output version
-    -h, --help                  output help information
+    -l, --clam-lib-path <dir>    path to ClamAV lib directory, default: $CLAM_LIB_DIR
+    -s, --state-file-path <dir>  path to state file directory, default: $STATE_FILE_DIR
+    -V, --version                output version
+    -h, --help                   output help information
 
   For more information, see https://github.com/tommarshall/nagios-check-clamav-signatures
 
@@ -61,6 +65,7 @@ while test $# -ne 0; do
   ARG=$1; shift
   case $ARG in
     -l|--clam-lib-path) CLAM_LIB_DIR=$1; shift ;;
+    -s|--state-file-path) STATE_FILE_DIR=$1; shift ;;
     -V|--version) version; exit ;;
     -h|--help) help; exit ;;
     *)
@@ -144,15 +149,36 @@ if ! [[ $CURRENT_MAIN_VERSION =~ $NUMERICAL_REGEX ]]; then
   exit $UNKNOWN
 fi
 
+# get the daily signatures timestamps
+LAST_OK_TIMESTAMP="$(stat --format='%Y' $STATE_FILE_DIR/$STATE_FILE_NAME 2>/dev/null || echo '0')"
+EXPIRY_THRESHOLD_TIMESTAMP="$(date --date="-$EXPIRY_THRESHOLD" +'%s')"
+
 # determine the difference between the current and installed versions
 DAILY_VERSION_DELTA=$((CURRENT_DAILY_VERSION-INSTALLED_DAILY_VERSION))
 MAIN_VERSION_DELTA=$((CURRENT_MAIN_VERSION-INSTALLED_MAIN_VERSION))
 
-if [ $DAILY_VERSION_DELTA -gt 0 -o $MAIN_VERSION_DELTA -gt 0 ]; then
+if [ $MAIN_VERSION_DELTA -gt 0 ]; then
   echo "CRITICAL: Signatures expired;" \
     "daily version: ${INSTALLED_DAILY_VERSION} (${DAILY_VERSION_DELTA} behind)," \
     "main version: ${INSTALLED_MAIN_VERSION} (${MAIN_VERSION_DELTA} behind)"
   exit $CRITICAL
+elif [ $DAILY_VERSION_DELTA -gt 0 ]; then
+  if [ $LAST_OK_TIMESTAMP -gt $EXPIRY_THRESHOLD_TIMESTAMP ]; then
+    echo "OK: Signatures expired, but within expiry threshold;" \
+      "daily version: ${INSTALLED_DAILY_VERSION} (${DAILY_VERSION_DELTA} behind)," \
+      "main version: ${INSTALLED_MAIN_VERSION} (${MAIN_VERSION_DELTA} behind)"
+    exit $OK
+  fi
+  echo "CRITICAL: Signatures expired;" \
+    "daily version: ${INSTALLED_DAILY_VERSION} (${DAILY_VERSION_DELTA} behind)," \
+    "main version: ${INSTALLED_MAIN_VERSION} (${MAIN_VERSION_DELTA} behind)"
+  exit $CRITICAL
+fi
+
+# modify the timestamp on the state file
+if ! touch $STATE_FILE_DIR/$STATE_FILE_NAME 2>/dev/null; then
+  echo "OK: Signatures up to date, but failed to write state file to ${STATE_FILE_DIR}/${STATE_FILE_NAME}"
+  exit $OK
 fi
 
 echo "OK: Signatures up to date;"\
