Exit unknown if unable to locate signature files

diff --git a/check_clamav_signatures b/check_clamav_signatures
--- a/check_clamav_signatures
+++ b/check_clamav_signatures
@@ -80,8 +80,21 @@ if [ ! -d "$CLAM_LIB_DIR" ]; then
   exit $UNKNOWN
 fi
 
-DAILY_SIGNATURES_PATH="${CLAM_LIB_DIR}/daily.cld"
-MAIN_SIGNATURES_PATH="${CLAM_LIB_DIR}/main.cvd"
+# ensure we have a daily signatures file
+if [ -e ${CLAM_LIB_DIR}/daily.cld ]; then
+  DAILY_SIGNATURES_PATH="${CLAM_LIB_DIR}/daily.cld"
+else
+  echo "UNKNOWN: Unable to locate installed daily signatures"
+  exit $UNKNOWN
+fi
+
+# ensure we have a main signatures file
+if [ -e ${CLAM_LIB_DIR}/main.cvd ]; then
+  MAIN_SIGNATURES_PATH="${CLAM_LIB_DIR}/main.cvd"
+else
+  echo "UNKNOWN: Unable to locate installed main signatures"
+  exit $UNKNOWN
+fi
 
 # extract the daily signatures version
 INSTALLED_DAILY_VERSION=$(sigtool -i ${DAILY_SIGNATURES_PATH} 2>/dev/null | grep Version | sed -e 's/Version: //')
