Exit unknown if clam lib dir does not exist

diff --git a/check_clamav_signatures b/check_clamav_signatures
--- a/check_clamav_signatures
+++ b/check_clamav_signatures
@@ -74,6 +74,12 @@ done
 # Showtime.
 #
 
+# ensure the clam lib dir exists
+if [ ! -d "$CLAM_LIB_DIR" ]; then
+  echo "UNKNOWN: Unable to locate ClamAV lib directory"
+  exit $UNKNOWN
+fi
+
 DAILY_SIGNATURES_PATH="${CLAM_LIB_DIR}/daily.cld"
 MAIN_SIGNATURES_PATH="${CLAM_LIB_DIR}/main.cvd"
 
